# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://instagram.com/victorfrnds">Instagram</a>'

style: dark # light (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
